CREATE TABLE IF NOT EXISTS roles(
id SERIAL PRIMARY KEY,
name varchar(20) NOT NULL
);

INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_MODERATOR');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');